- name: install
  hosts: localhost
  become: true

  tasks:

    - name: "include vars files"
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "add yum repos"
      ansible.builtin.yum_repository:
        name: "{{ item.yum_repo_name }}"
        baseurl: "{{ item.yum_repo_baseurl }}"
        description: "{{ item.yum_repo_description }}"
        enabled: "{{ item.yum_repo_enabled }}"
        file: "{{ item.yum_repo_file }}"
        gpgcheck: "{{ item.yum_repo_gpgcheck }}"
        gpgkey: "{{ item.yum_repo_gpgkey }}"
      loop: "{{ yum_repo_list }}"

    - name: "install dnf packages"
      ansible.builtin.dnf:
        name: "{{ install_list }}"
        state: "latest"
    
    - name: "enable and start services"
      ansible.builtin.systemd:
        name: "docker"
        state: started
        enabled: true

    - name: "configure users"
      ansible.builtin.user:
        name: "rross"
        generate_ssh_key: true
        groups: "docker,wheel"
        shell: "/bin/fish"
        ssh_key_bits: 2048
        ssh_key_file: ".ssh/id_rsa"
      tags:
        - users

    - name: "template shell configs"
      ansible.builtin.template:
        src: "config.fish.j2"
        dest: "/home/{{ lookup('env', 'USER') }}/.config/fish/config.fish"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      tags:
        - shell
        - fish
...
#EOF