- name: install
  hosts: localhost
  become: true

  tasks:

    - name: "include vars files"
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "add yum repos"
      ansible.builtin.yum_repository:
        name: "{{ item.yum_repo_name }}"
        baseurl: "{{ item.yum_repo_baseurl }}"
        description: "{{ item.yum_repo_description }}"
        enabled: "{{ item.yum_repo_enabled }}"
        file: "{{ item.yum_repo_file }}"
        gpgcheck: "{{ item.yum_repo_gpgcheck }}"
        gpgkey: "{{ item.yum_repo_gpgkey }}"
      loop: "{{ yum_repo_list }}"

    - name: "install dnf packages"
      ansible.builtin.dnf:
        name: "{{ install_list }}"
        state: "latest"
