- name: install
  hosts: localhost
  become: true
  tasks:
    - name: "add vscode repo"
      ansible.builtin.yum_repository:
        name: "code"
        baseurl: "https://packages.microsoft.com/yumrepos/vscode"
        description: "Visual Studio Code repo"
        enabled: true
        file: "vscode"
        gpgcheck: true
        gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

    - name: "install vscode"
      ansible.builtin.dnf:
        name:
          - "code"
        state: "latest"
