- name: install
  hosts: localhost
  become: true

  tasks:

    - name: "include vars files"
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "add yum repos"
      ansible.builtin.yum_repository:
        name: "{{ item.yum_repo_name }}"
        baseurl: "{{ item.yum_repo_baseurl }}"
        description: "{{ item.yum_repo_description }}"
        enabled: "{{ item.yum_repo_enabled }}"
        file: "{{ item.yum_repo_file }}"
        gpgcheck: "{{ item.yum_repo_gpgcheck }}"
        gpgkey: "{{ item.yum_repo_gpgkey }}"
      loop: "{{ yum_repo_list }}"

    - name: "install dnf packages"
      ansible.builtin.dnf:
        name: "{{ dnf_install_list }}"
        state: "latest"
    
    - name: "enable and start services"
      ansible.builtin.systemd:
        name: "docker"
        state: started
        enabled: true


    ##################################
    ### create and configure users ###
    ##################################
    - name: "configure users"
      ansible.builtin.user:
        name: "rross"
        generate_ssh_key: true
        groups: "docker,wheel"
        shell: "/bin/fish"
        ssh_key_bits: 2048
        ssh_key_file: ".ssh/id_rsa"
      tags:
        - users

    - name: "template shell configs"
      ansible.builtin.template:
        src: "config.fish.j2"
        dest: "/home/{{ lookup('env', 'USER') }}/.config/fish/config.fish"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      tags:
        - shell
        - fish

    - name: "create omf directories"
      ansible.builtin.file:
        path: "/home/{{ lookup('env', 'USER') }}/{{ item }}/"
        state: "directory"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0644
      loop:
        - ".local/share/omf"
        - ".config/omf"
      tags:
        - fish
        - omf

    - name: "get oh-my-fish installer"
      ansible.builtin.get_url:
        url: "https://get.oh-my.fish"
        dest: "/home/{{ lookup('env', 'USER') }}/.local/share/omf/omf"
        checksum: sha256:bb1f4025934600ea6feef2ec11660e17e2b6449c5a23c033860aed712ad328c9
      tags:
        - fish
        - omf

    - name: "isntall oh-my-fish"
      ansible.builtin.command: "fish install --path=/home/{{ lookup('env', 'USER') }}/.local/share/omf --config=/home/{{ lookup('env', 'USER') }}/.config/omf"
      args:
        chdir: "/home/{{ lookup('env', 'USER') }}/.local/share/omf"
      tags:
        - fish
        - omf
...
#EOF