# main.yaml

# tasks to install or config fish shell
---

# TODO: wrap the install part in a conditioanal if ansible_facts.ansible_env.shell != "/bin/fish" - https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
- name: "add fish apt repo"
  ansible.builtin.command: "apt-add-repository ppa:fish-shell/release-3"
  become: true

- name: "update apt cache"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "install fish"
  ansible.builtin.apt:
    name: "fish"
    state: present
  become: true

- name: "create fish shell config directory"
  ansible.builtin.file:
    path: "/home/{{ lookup('env', 'USER') }}/.config/fish/conf.d"
    state: "directory"

- name: "template shell configs" 
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/fish/conf.d/{{ item }}.fish"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0644
  loop:
    - "config"
   #  - "work_envs"
  tags:
    - "shell"
    - "fish"

- name: "check for oh-my-fish installer"
  ansible.builtin.stat:
    path: "/home/{{ lookup('env', 'USER') }}/omf-install"
  register: omf_installed
  tags: 
    - "fish"
    - "shell"

- name: "create fish complections directory"
  ansible.builtin.file:
    group: "{{ lookup('env', 'USER') }}"
    mode: 0770
    owner: "{{ lookup('env', 'USER') }}"
    path: "/home/{{ lookup('env', 'USER') }}/.config/fish/conf.d/completions"
    state: "directory"
  tags:
    - "fish"
    - "shell"

- name: "copy fish completions"
  ansible.builtin.copy:
    dest: "/home/{{ lookup('env', 'USER') }}/.config/fish/conf.d/{{ item }}.fish"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0644
    src: "files/{{ item }}.fish"
  loop: 
    - "kubectx"
    - "kubens"
  tags:
    - "fish"
    - "shell"

- name: "block for installing omf"
  block:

    - name: "get oh-my-fish installer"
      ansible.builtin.get_url:
        checksum: "sha256:bb1f4025934600ea6feef2ec11660e17e2b6449c5a23c033860aed712ad328c9"
        dest: "/home/{{ lookup('env', 'USER') }}/omf-install"
        group: "{{ lookup('env', 'USER') }}"
        mode: 0700
        owner: "{{ lookup('env', 'USER') }}"
        url: "https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install"
      tags:
        - fish
        - omf

    # TODO: check if omf is installed because this will hang
    - name: "install oh-my-fish package manager"
      ansible.builtin.command: 
        cmd: "fish omf-install"
      args:
        chdir: "/home/{{ lookup('env', 'USER') }}"
      tags:
        - fish
        - omf

    - name: "remove oh-my-fish installer"
      ansible.builtin.file:
        path: "/home/{{ lookup('env', 'USER') }}/omf-install"
        state: "absent"
      tags:
        - fish
        - omf

  when: not omf_installed.stat.exists
...
#EOF